In [1]:
import pandas as pd

In [2]:
# Q1. Pandas version
pd.__version__

'2.2.2'

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv')

In [4]:
# Q2. Records count
df.shape[0]

2160

In [ ]:
# df.info()

In [5]:
# Q3. Laptop brands
df.Brand.nunique(dropna=True)

27

In [6]:
# Q4. Missing values
df.isna().any().sum()

np.int64(3)

In [7]:
# Q5. Maximum final price
df[df.Brand == 'Dell']['Final Price'].max()

np.float64(3936.0)

In [8]:
# Q6. Median value of Screen
# (1)
df.Screen.median()

np.float64(15.6)

In [10]:
# (2)
df['Screen'].value_counts().head(1)

Screen
15.6    1009
Name: count, dtype: int64

In [9]:
df['Screen'].mode()

0    15.6
Name: Screen, dtype: float64

In [13]:
# (3) 
result = df['Screen'].value_counts().head(1)
fill_value = result.iloc[0]

df['Screen'] = df['Screen'].fillna(fill_value)

In [14]:
# (4)
df.Screen.median()

# result - the median did not change (not mode also did not change but the mean did change)

np.float64(15.6)

In [5]:
# Q7. Sum of weights
# (1)
df = df[df.Brand == 'Innjoo']

In [ ]:
df

In [7]:
# (2)
df = df[['RAM', 'Storage', 'Screen']]

In [8]:
df

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [9]:
# (3)
x = df.values

In [10]:
x

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [14]:
# (4)
import numpy as np

In [15]:
# xt = np.matrix_transpose(x)
xt = x.T

In [16]:
xt

array([[  8. ,   8. ,   4. ,   6. ,   6. ,   6. ],
       [256. , 512. ,  64. ,  64. , 128. , 128. ],
       [ 15.6,  15.6,  14.1,  14.1,  14.1,  14.1]])

In [20]:
# xtx = x.dot(xt)
xtx = xt.dot(x)

In [18]:
xtx

array([[ 65843.36, 131379.36,  16635.96,  16651.96,  33035.96,  33035.96],
       [131379.36, 262451.36,  33019.96,  33035.96,  65803.96,  65803.96],
       [ 16635.96,  33019.96,   4310.81,   4318.81,   8414.81,   8414.81],
       [ 16651.96,  33035.96,   4318.81,   4330.81,   8426.81,   8426.81],
       [ 33035.96,  65803.96,   8414.81,   8426.81,  16618.81,  16618.81],
       [ 33035.96,  65803.96,   8414.81,   8426.81,  16618.81,  16618.81]])

In [21]:
xtx

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [ ]:
# xtx.shape

In [ ]:
# np.linalg.det(xtx)

In [23]:
# (5)
xtx_inverse = np.linalg.inv(xtx)
xtx_inverse

# matrix_inverse = np.linalg.inv(xtx)
# np.linalg.pinv(xtx)

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [ ]:
# (6)

In [26]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])

In [27]:
y

array([1100, 1300,  800,  900, 1000, 1100])

In [25]:
# (7)
result = xtx_inverse.dot(xt)
result

array([[ 0.26298349, -0.12560233, -0.40646389,  0.14958687,  0.05244042,
         0.05244042],
       [-0.00110155,  0.00295059,  0.00125892, -0.00177691, -0.00076387,
        -0.00076387],
       [-0.08772226,  0.0269791 ,  0.17140891, -0.0302108 , -0.00153546,
        -0.00153546]])

In [29]:
w = result.dot(y)
w

array([45.58076606,  0.42783519, 45.29127938])

In [30]:
# (8)
w.sum()

np.float64(91.2998806299555)

In [ ]:
# working area

In [12]:
# before
df.Screen.mean()

np.float64(15.168112244897959)

In [15]:
# after
df.Screen.mean()

np.float64(17.008541666666666)

In [16]:
df['Screen'].mode()

0    15.6
Name: Screen, dtype: float64